name: Publish docker image
on:
    push:
        branches: [main]
env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}
    IMAGE_NAME_UI: ${{ github.repository }}.ui
jobs:
    tag_repo:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Extract version from cmd/sub/version.go
              id: get_version
              run: |
                  TAG_NAME=v$(grep "const Version =" cmd/sub/version.go | grep "const Version =" | sed -e 's-.*= "--' -e 's-".*--')
                  echo "tag_name=$TAG_NAME" >> $GITHUB_ENV
            - name: Create a tag
              env:
                  TAG_NAME: ${{ env.tag_name }}
              uses: actions/github-script@v5
              with:
                  script: |
                      github.rest.git.createRef({
                      owner: context.repo.owner,
                      repo: context.repo.repo,
                      ref: `refs/tags/${process.env.TAG_NAME}`,
                      sha: context.sha
                      })
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: build normal docker image
              run: make build-docker
            - name: build ui image
              run: make build-docker-ui
            - name: Login to GitHub Registry
              run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u okieoth --password-stdin
            - name: Push the Docker image
              run: make docker-push
            - name: Push the ui Docker image
              run: make docker-ui-push
            - name: Create GitHub Release
              uses: softprops/action-gh-release@v2
              with:
                  tag_name: ${{ env.tag_name }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
